experiment_name: "SNN_ResNet18_RateEncoding"
description: "Spiking ResNet-18 U-Net with standard LIF neurons and Rate encoding. (SANITY CHECK)"

data:
  dataset_path: "/path/to/your/deap/data"
  encoding_method: "rate"
  num_timesteps: 10

mask:
  type: "quadrant_gaussian"
  sigma: 8.0

model:
  type: "SpikingUNet"
  encoder_type: "ResNet34"
  in_channels: 5
  num_classes: 2

neuron_params:
  spike_model: "snn.Synaptic" 
  beta: 0.9
  alpha: 0.5
  threshold: 1.0

training:
  epochs: 100
  batch_size: 16
  learning_rate: 0.001

loss:
  smooth: 0.
  lambda_bce: 1.0
  lambda_class: 0.1

logging:
  project_name: "snn-encoding-showdown"  # The name of the project on the website
  run_name: "Sanity_ResNet34_Latency"    # A specific name for this experiment
  tags: ["sanity-check", "resnet34", "latency", "snn"] # Tags for filtering later
  offline: false   # Set to true if you have no internet and want to sync later